# Generated by Django 5.2.11 on 2026-02-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Requests'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='component',
        ),
        migrations.RemoveField(
            model_name='request',
            name='quantity',
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.request')),
            ],
        ),
    ]
