# Generated by Django 5.2.11 on 2026-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_options_alter_component_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
