# Generated by Django 5.2.11 on 2026-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_requestitem_issued_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='return_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
