# Generated by Django 5.2.11 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
