# Generated by Django 5.2.11 on 2026-02-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_request_status_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
